services:
  sitrate_backend:
    build: ./
    ports:
      - 12345:12345
    depends_on:
      - sitrate_h2

  sitrate_h2:
    image: 1000kit/h2
    ports:
      - "8181:8181"
      - "1521:1521"
    volumes:
      - h2-data:/opt/h2-data

volumes:
  h2-data:
